[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "c-cxx-project-template"
version = "0.1.0"
description = "A template repository for C/C++ projects with CMake and Conan. A GitHub Action workflow is provided with the on workflow_dispatch event. This event has a Project Type input that lets the user configure this template as a C executable, static library, shared library, or an interface library which is header only."
requires-python = ">=3.12"

dependencies = [
    "jinja2",
    "click",
]

[project.scripts]
create-project = "project.main:main"

